name: Worker Master Branch Merge

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/worker-master.yml"
      - "worker/**"

  workflow_dispatch:

env:
  IMAGE_NAME: worker

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.IMAGE_NAME }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Image Metadata
        id: imagemeta
        uses: docker/metadata-action@v4
        with:
          images: |
            arho0/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=ref,event=tag
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ env.IMAGE_NAME }}/
          file: ./${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          tags: ${{ steps.imagemeta.outputs.tags }}
          labels: ${{ steps.imagemeta.outputs.labels }}

  
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    -
      name: Set Context
      uses: azure/k8s-set-context@v3
      with:
        method: service-account
        k8s-url: ${{ secrets.CLUSTER_ADDR }}
        k8s-secret: ${{ secrets.CLUSTER_SECRET }}
    -
      name: Checkout Source
      uses: actions/checkout@v3
    - 
      name: Replace GITHUB_SHA in Manifest
      run: sed -i "s/GITHUB_SHA/votingprod/g" ./kube-deployment-prod.yml
    -
      name: Deploy to the Cluster
      uses: azure/k8s-deploy@v4
      with:
        namespace: votingprod
        manifests: |
          ./kube-deployment-prod.yml
        images: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    - 
      name: Create DNS Record for Vote
      uses: infraway/create-dns-record@v2.0
      with:
        type: "CNAME"
        name: "${{ github.sha }}-vote.${{ secrets.CF_ZONE_ADDRESS }}"
        content: "${{ secrets.CF_ZONE_ADDRESS }}"
        ttl: 1
        proxied: true
        token: ${{ secrets.CF_API_TOKEN }}
        zone: ${{ secrets.CF_ZONE_ID }}
    - 
      name: Create DNS Record for Result
      uses: infraway/create-dns-record@v2.0
      with:
        type: "CNAME"
        name: "${{ github.sha }}-result.${{ secrets.CF_ZONE_ADDRESS }}"
        content: "${{ secrets.CF_ZONE_ADDRESS }}"
        ttl: 1
        proxied: true
        token: ${{ secrets.CF_API_TOKEN }}
        zone: ${{ secrets.CF_ZONE_ID }}
