name: Vote Branch Build

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "vote/**"
      - ".github/workflows/worker-branch.yml"

  workflow_dispatch:

env:
  IMAGE_NAME: workerapp

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME
          tags: |
            type=ref,event=pr
            type=ref,event=push
            type=sha

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
