name: Worker Branch Build

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "vote/**"
      - ".github/workflows/worker-branch.yml"

  workflow_dispatch:

env:
  IMAGE_NAME: workerapp

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./worker/
          file: ./worker/Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

  
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    -
      name: Set Context
      uses: azure/k8s-set-context@v3
      with:
        method: service-account
        k8s-url: ${{ secrets.CLUSTER_ADDR }}
        k8s-secret: ${{ secrets.CLUSTER_SECRET }}
    -
      name: Checkout Source
      uses: actions/checkout@v3
    -
      name: Replace Kubernetes Namespace with SHA
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "DEST_NAMESPACE"
        replace: "${{ github.sha }}"
        include: "./kube-deployment.yml"
        regex: true
    -
      name: Replace Kubernetes Namespace with SHA
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "VOTE_ADDRESS"
        replace: "${{ github.sha }}"
        include: "./kube-deployment.yml"
        regex: true
    -
      name: Replace Kubernetes VOTE ADDRESS with SHA
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "RESULT_ADDRESS"
        replace: "${{ github.sha }}"
        include: "./kube-deployment.yml"
        regex: true
    -
      name: Deploy to the Cluster
      uses: azure/k8s-deploy@v4
      with:
        namespace: hardcoded-ns
        manifests: |
          ./kube-deployment.yml
        # images: |
        #   ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    #Create a new Kubernetes Namespace
    #Deploy App Components to the Namespace

